name: WINDOWS Lint & Type Check

env:
  PYTHON_VERSION: "3.12"
  POETRY_VERSION: "1.8.3"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint_type_check:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache poetry
        id: poetry-cache
        uses: actions/cache@v4
        with:
          path: ~\AppData\Roaming\Python\Scripts
          key: ${{ runner.os }}-python${{ env.PYTHON_VERSION }}-poetry${{ env.POETRY_VERSION }}
      - name: Cache poetry packages
        id: packages-cache
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pypoetry\Cache\virtualenvs
          key: ${{ runner.os }}-${{ github.job }}-packages-${{ hashFiles('**/poetry.lock') }}
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install poetry
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version ${{ env.POETRY_VERSION }}
      - name: Add Poetry to PATH
        shell: bash
        run: echo "$APPDATA/Python/Scripts" >> $GITHUB_PATH
      - name: Check current directory
        shell: bash
        run: pwd
      - name: Resolve Dependencies
        if: steps.packages-cache.outputs.cache-hit != 'true'
        shell: bash
        run: poetry install
      - name: Run ruff
        shell: bash
        run: poetry run ruff check
      - name: Run mypy
        shell: bash
        run: poetry run mypy .
